// app/pages/PlatformAdmin/PointsManagement/components/ServiceItemDialog.tsx
/**
 * 平台后台 - 积分服务项弹窗（奖励/换购）
 */

import { Form } from '@remix-run/react'
import type { PointsRewardItem, PointsExchangeItem } from '../types/valueAddedService.types'
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '~/components/ui/dialog'
import { Button } from '~/components/ui/button'
import { Input } from '~/components/ui/input'
import { Label } from '~/components/ui/label'

interface ServiceItemDialogProps {
  open: boolean
  onOpenChange: (open: boolean) => void
  mode: 'create' | 'edit'
  type: 'reward' | 'exchange' // 奖励或换购
  item?: PointsRewardItem | PointsExchangeItem | null
}

export default function ServiceItemDialog({
  open,
  onOpenChange,
  mode,
  type,
  item,
}: ServiceItemDialogProps) {
  const isReward = type === 'reward'
  const title = mode === 'create'
    ? `新增${isReward ? '积分奖励' : '积分换购'}服务`
    : `编辑${isReward ? '积分奖励' : '积分换购'}服务`

  // 确定action路径
  const actionPath = mode === 'create'
    ? `/platform-admin/points-management/services`
    : `/platform-admin/points-management/services`

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-[500px]">
        <DialogHeader>
          <DialogTitle className="text-lg font-semibold text-slate-900">{title}</DialogTitle>
        </DialogHeader>

        <Form method="post" action={actionPath} className="space-y-4 mt-4">
          {/* Hidden fields */}
          <input type="hidden" name="action" value={mode === 'create' ? `create-${type}` : `update-${type}`} />
          {mode === 'edit' && item && <input type="hidden" name="id" value={item.id} />}

          {/* 服务内容 */}
          <div className="space-y-2">
            <Label htmlFor="serviceName" className="text-sm font-medium text-slate-700">
              服务内容 <span className="text-red-500">*</span>
            </Label>
            <Input
              id="serviceName"
              name="serviceName"
              defaultValue={item?.serviceName || ''}
              placeholder="请输入服务内容（最多50字符）"
              maxLength={50}
              required
              className="h-9 border-slate-300 focus:border-blue-500 focus:ring-2 focus:ring-blue-500/20"
            />
          </div>

          {/* 积分数量 */}
          <div className="space-y-2">
            <Label htmlFor="pointsAmount" className="text-sm font-medium text-slate-700">
              {isReward ? '奖励积分' : '消耗积分'} <span className="text-red-500">*</span>
            </Label>
            <Input
              id="pointsAmount"
              name="pointsAmount"
              type="number"
              min="1"
              defaultValue={
                item
                  ? isReward
                    ? (item as PointsRewardItem).pointsReward
                    : (item as PointsExchangeItem).pointsCost
                  : ''
              }
              placeholder="请输入积分数量（正整数）"
              required
              className="h-9 border-slate-300 focus:border-blue-500 focus:ring-2 focus:ring-blue-500/20"
            />
          </div>

          {/* 按钮组 */}
          <div className="flex justify-end gap-3 pt-4">
            <Button
              type="button"
              variant="outline"
              onClick={() => onOpenChange(false)}
              className="h-9 px-4 border-slate-300"
            >
              取消
            </Button>
            <Button
              type="submit"
              className="h-9 px-4 bg-blue-600 hover:bg-blue-700 text-white"
              onClick={() => {
                // 提交后关闭弹窗
                setTimeout(() => onOpenChange(false), 100)
              }}
            >
              {mode === 'create' ? '创建' : '保存'}
            </Button>
          </div>
        </Form>
      </DialogContent>
    </Dialog>
  )
}

// src/views/PlatformAdmin/PointsManagement/components/ServiceItemDialog.vue
<template>
  <a-modal
    :visible="value"
    :title="title"
    width="500px"
    :confirm-loading="loading"
    @ok="handleSubmit"
    @cancel="handleCancel"
  >
    <a-form-model ref="formRef" :model="form" :rules="rules">
      <!-- 服务内容 -->
      <a-form-model-item label="服务内容" prop="serviceName">
        <a-input
          v-model="form.serviceName"
          placeholder="请输入服务内容（最多50字符）"
          :maxLength="50"
        />
      </a-form-model-item>

      <!-- 积分数量 -->
      <a-form-model-item :label="pointsLabel" prop="pointsAmount">
        <a-input-number
          v-model="form.pointsAmount"
          :min="1"
          :precision="0"
          placeholder="请输入积分数量（正整数）"
          style="width: 100%"
        />
      </a-form-model-item>
    </a-form-model>
  </a-modal>
</template>

<script lang="ts">
import { defineComponent, reactive, ref, computed, watch } from '@vue/composition-api'
import ValueAddedServiceService from '../services/valueAddedService.service'
import type { PointsRewardItem, PointsExchangeItem } from '../types/valueAddedService.types'

export default defineComponent({
  name: 'ServiceItemDialog',

  props: {
    value: {
      type: Boolean,
      default: false
    },
    mode: {
      type: String as () => 'create' | 'edit',
      required: true
    },
    type: {
      type: String as () => 'reward' | 'exchange',
      required: true
    },
    item: {
      type: Object as () => PointsRewardItem | PointsExchangeItem | null,
      default: null
    }
  },

  setup(props, { emit }) {
    const loading = ref(false)
    const formRef = ref<any>(null)

    const form = reactive({
      serviceName: '',
      pointsAmount: undefined as number | undefined
    })

    const rules = {
      serviceName: [
        { required: true, message: '请输入服务内容', trigger: 'blur' },
        { max: 50, message: '服务内容不能超过50字符', trigger: 'blur' }
      ],
      pointsAmount: [
        { required: true, message: '请输入积分数量', trigger: 'blur' },
        { type: 'number', min: 1, message: '积分数量必须大于0', trigger: 'blur' }
      ]
    }

    const isReward = computed(() => props.type === 'reward')
    const title = computed(() => {
      const typeText = isReward.value ? '积分奖励' : '积分换购'
      return props.mode === 'create' ? `新增${typeText}服务` : `编辑${typeText}服务`
    })
    const pointsLabel = computed(() => isReward.value ? '奖励积分' : '消耗积分')

    // 监听item变化，更新表单
    watch(() => props.item, (newItem) => {
      if (newItem && props.mode === 'edit') {
        form.serviceName = newItem.serviceName
        if (isReward.value) {
          form.pointsAmount = (newItem as PointsRewardItem).pointsReward
        } else {
          form.pointsAmount = (newItem as PointsExchangeItem).pointsCost
        }
      }
    }, { immediate: true })

    // 监听visible变化，重置表单
    watch(() => props.value, (visible) => {
      if (!visible) {
        form.serviceName = ''
        form.pointsAmount = undefined
        formRef.value?.resetFields()
      } else if (visible && props.mode === 'create') {
        form.serviceName = ''
        form.pointsAmount = undefined
      }
    })

    const handleSubmit = async () => {
      try {
        await formRef.value?.validate()

        loading.value = true

        if (props.mode === 'create') {
          // 创建
          if (isReward.value) {
            await ValueAddedServiceService.createRewardService({
              serviceName: form.serviceName,
              pointsReward: form.pointsAmount!,
              status: 'active'
            })
          } else {
            await ValueAddedServiceService.createExchangeService({
              serviceName: form.serviceName,
              pointsCost: form.pointsAmount!,
              status: 'active'
            })
          }
        } else {
          // 编辑
          if (!props.item) return

          if (isReward.value) {
            await ValueAddedServiceService.updateRewardService(props.item.id, {
              serviceName: form.serviceName,
              pointsReward: form.pointsAmount!
            })
          } else {
            await ValueAddedServiceService.updateExchangeService(props.item.id, {
              serviceName: form.serviceName,
              pointsCost: form.pointsAmount!
            })
          }
        }

        emit('input', false)
        emit('success')
      } catch (error) {
        console.error('提交失败:', error)
      } finally {
        loading.value = false
      }
    }

    const handleCancel = () => {
      emit('input', false)
    }

    return {
      loading,
      formRef,
      form,
      rules,
      title,
      pointsLabel,
      handleSubmit,
      handleCancel
    }
  }
})
</script>

<style scoped lang="less">
// 自定义样式
</style>
