// src/views/PlatformAdmin/PointsManagement/PointsConfigPage.vue
<template>
  <sidebar>
    <div class="page-container">
      <!-- ServiceItem Dialogs -->
      <service-item-dialog
        v-model="isRewardCreateDialogOpen"
        mode="create"
        type="reward"
        @success="handleDialogSuccess"
      />
      <service-item-dialog
        v-model="isRewardEditDialogOpen"
        mode="edit"
        type="reward"
        :item="editingRewardItem"
        @success="handleDialogSuccess"
      />
      <service-item-dialog
        v-model="isExchangeCreateDialogOpen"
        mode="create"
        type="exchange"
        @success="handleDialogSuccess"
      />
      <service-item-dialog
        v-model="isExchangeEditDialogOpen"
        mode="edit"
        type="exchange"
        :item="editingExchangeItem"
        @success="handleDialogSuccess"
      />

      <!-- Card 1: 基础规则配置 -->
      <a-card class="card-style" :bordered="false">
        <div slot="title" class="flex items-center justify-between">
          <span class="card-title">积分基础规则</span>
          <div v-if="!isEditingBaseRule">
            <a-button type="primary" class="btn-style" @click="isEditingBaseRule = true">
              编辑
            </a-button>
          </div>
          <div v-else class="flex gap-2">
            <a-button type="primary" class="btn-style" @click="handleSaveBaseRule">
              保存
            </a-button>
            <a-button class="btn-style-outline" @click="handleCancelEditBaseRule">
              取消
            </a-button>
          </div>
        </div>

        <!-- 第一行：5个基础配置 -->
        <div v-if="baseRule" class="grid-5 mb-6">
          <div class="field-item">
            <label>注册奖励</label>
            <div v-if="isEditingBaseRule" class="input-with-unit">
              <a-input-number
                v-model="baseRuleForm.registerReward"
                :min="0"
                class="input-style"
              />
              <span class="unit-text">积分</span>
            </div>
            <div v-else class="value-display">
              <span>{{ baseRule.registerReward }}积分</span>
            </div>
          </div>

          <div class="field-item">
            <label>邀请人奖励</label>
            <div v-if="isEditingBaseRule" class="input-with-unit">
              <a-input-number
                v-model="baseRuleForm.inviterReward"
                :min="0"
                class="input-style"
              />
              <span class="unit-text">积分</span>
            </div>
            <div v-else class="value-display">
              <span>{{ baseRule.inviterReward }}积分</span>
            </div>
          </div>

          <div class="field-item">
            <label>积分兑换汇率</label>
            <div v-if="isEditingBaseRule" class="input-with-unit">
              <a-input-number
                v-model="baseRuleForm.exchangeRate"
                :min="1"
                class="input-style"
              />
              <span class="unit-text">积分=1元</span>
            </div>
            <div v-else class="value-display">
              <span>{{ baseRule.exchangeRate }}积分=1元</span>
            </div>
          </div>

          <div class="field-item">
            <label>最大抵扣比例</label>
            <div v-if="isEditingBaseRule" class="input-with-unit">
              <a-input-number
                v-model="baseRuleForm.maxDeductionRatio"
                :min="0"
                :max="100"
                class="input-style"
              />
              <span class="unit-text">%</span>
            </div>
            <div v-else class="value-display">
              <span>{{ baseRule.maxDeductionRatio }}%</span>
            </div>
          </div>

          <div class="field-item">
            <label>积分有效期</label>
            <div v-if="isEditingBaseRule" class="input-with-unit">
              <a-input-number
                v-model="baseRuleForm.validityMonths"
                :min="1"
                class="input-style"
              />
              <span class="unit-text">月</span>
            </div>
            <div v-else class="value-display">
              <span>{{ baseRule.validityMonths }}个月</span>
            </div>
          </div>
        </div>

        <!-- 第二行：入住返还倍数 -->
        <div v-if="baseRule" class="vip-multipliers">
          <label class="mb-3 block">入住返还倍数</label>
          <div class="grid-10">
            <div v-for="idx in 10" :key="idx" class="vip-item">
              <div class="vip-label">VIP{{ idx - 1 }}</div>
              <div v-if="isEditingBaseRule">
                <a-input-number
                  v-model="baseRuleForm[`vip${idx - 1}`]"
                  :min="1"
                  :step="0.1"
                  class="vip-input"
                />
              </div>
              <div v-else class="vip-value">
                <span>{{ baseRule.vipMultipliers[`VIP${idx - 1}`]?.toFixed(1) }}</span>
              </div>
            </div>
          </div>
        </div>
      </a-card>

      <!-- Card 2: 积分奖励服务 -->
      <a-card class="card-style" :bordered="false">
        <div slot="title" class="flex items-center justify-between">
          <span class="card-title">积分奖励服务</span>
          <a-button type="primary" class="btn-style" @click="isRewardCreateDialogOpen = true">
            <a-icon type="plus" />
            新增
          </a-button>
        </div>

        <div class="table-wrapper">
          <a-table
            :columns="rewardColumns"
            :data-source="rewardServices"
            :pagination="false"
            row-key="id"
          >
            <template slot="order" slot-scope="text, record">
              <span>{{ record.序号 }}</span>
            </template>

            <template slot="serviceName" slot-scope="serviceName">
              <span class="font-medium">{{ serviceName }}</span>
            </template>

            <template slot="pointsReward" slot-scope="pointsReward">
              <span class="text-green-600 font-semibold">+{{ pointsReward }}</span>
            </template>

            <template slot="action" slot-scope="text, record, index">
              <div class="action-buttons">
                <a-button
                  size="small"
                  :disabled="index === 0"
                  @click="handleMoveReward(index, 'up')"
                >
                  <a-icon type="up" />
                </a-button>

                <a-button
                  size="small"
                  :disabled="index === rewardServices.length - 1"
                  @click="handleMoveReward(index, 'down')"
                >
                  <a-icon type="down" />
                </a-button>

                <a-button size="small" @click="handleEditReward(record)">
                  <a-icon type="edit" />
                  编辑
                </a-button>

                <a-button size="small" class="btn-delete" @click="handleDeleteReward(record.id)">
                  <a-icon type="delete" />
                  删除
                </a-button>
              </div>
            </template>
          </a-table>
        </div>
      </a-card>

      <!-- Card 3: 积分换购服务 -->
      <a-card class="card-style" :bordered="false">
        <div slot="title" class="flex items-center justify-between">
          <span class="card-title">积分换购服务</span>
          <a-button type="primary" class="btn-style" @click="isExchangeCreateDialogOpen = true">
            <a-icon type="plus" />
            新增
          </a-button>
        </div>

        <div class="table-wrapper">
          <a-table
            :columns="exchangeColumns"
            :data-source="exchangeServices"
            :pagination="false"
            row-key="id"
          >
            <template slot="order" slot-scope="text, record">
              <span>{{ record.序号 }}</span>
            </template>

            <template slot="serviceName" slot-scope="serviceName">
              <span class="font-medium">{{ serviceName }}</span>
            </template>

            <template slot="pointsCost" slot-scope="pointsCost">
              <span class="text-red-600 font-semibold">-{{ Math.abs(pointsCost) }}</span>
            </template>

            <template slot="action" slot-scope="text, record, index">
              <div class="action-buttons">
                <a-button
                  size="small"
                  :disabled="index === 0"
                  @click="handleMoveExchange(index, 'up')"
                >
                  <a-icon type="up" />
                </a-button>

                <a-button
                  size="small"
                  :disabled="index === exchangeServices.length - 1"
                  @click="handleMoveExchange(index, 'down')"
                >
                  <a-icon type="down" />
                </a-button>

                <a-button size="small" @click="handleEditExchange(record)">
                  <a-icon type="edit" />
                  编辑
                </a-button>

                <a-button size="small" class="btn-delete" @click="handleDeleteExchange(record.id)">
                  <a-icon type="delete" />
                  删除
                </a-button>
              </div>
            </template>
          </a-table>
        </div>
      </a-card>
    </div>
  </sidebar>
</template>

<script lang="ts">
import { defineComponent, ref, reactive, onMounted } from '@vue/composition-api'
import Sidebar from '@/components/Layout/Sidebar.vue'
import ServiceItemDialog from './components/ServiceItemDialog.vue'
import ValueAddedServiceService from './services/valueAddedService.service'
import type { PointsBaseRule, PointsRewardItem, PointsExchangeItem } from './types/valueAddedService.types'

export default defineComponent({
  name: 'PointsConfigPage',
  components: {
    Sidebar,
    ServiceItemDialog
  },

  setup() {
    // ========== 数据状态 ==========
    const baseRule = ref<PointsBaseRule | null>(null)
    const rewardServices = ref<PointsRewardItem[]>([])
    const exchangeServices = ref<PointsExchangeItem[]>([])

    // ========== 基础规则编辑 ==========
    const isEditingBaseRule = ref(false)
    const baseRuleForm = reactive({
      registerReward: 0,
      inviterReward: 0,
      exchangeRate: 0,
      maxDeductionRatio: 0,
      validityMonths: 0,
      vip0: 1.0,
      vip1: 1.2,
      vip2: 1.4,
      vip3: 1.6,
      vip4: 1.8,
      vip5: 2.0,
      vip6: 2.3,
      vip7: 2.6,
      vip8: 2.9,
      vip9: 3.2
    })

    // ========== Dialog状态 ==========
    const isRewardCreateDialogOpen = ref(false)
    const isRewardEditDialogOpen = ref(false)
    const editingRewardItem = ref<PointsRewardItem | null>(null)

    const isExchangeCreateDialogOpen = ref(false)
    const isExchangeEditDialogOpen = ref(false)
    const editingExchangeItem = ref<PointsExchangeItem | null>(null)

    // ========== 表格配置 ==========
    const rewardColumns = [
      { title: '序号', width: 80, scopedSlots: { customRender: 'order' } },
      { title: '服务内容', dataIndex: 'serviceName', scopedSlots: { customRender: 'serviceName' } },
      { title: '奖励积分', dataIndex: 'pointsReward', width: 120, scopedSlots: { customRender: 'pointsReward' } },
      { title: '操作', width: 280, align: 'center', scopedSlots: { customRender: 'action' } }
    ]

    const exchangeColumns = [
      { title: '序号', width: 80, scopedSlots: { customRender: 'order' } },
      { title: '服务内容', dataIndex: 'serviceName', scopedSlots: { customRender: 'serviceName' } },
      { title: '消耗积分', dataIndex: 'pointsCost', width: 120, scopedSlots: { customRender: 'pointsCost' } },
      { title: '操作', width: 340, align: 'center', scopedSlots: { customRender: 'action' } }
    ]

    // ========== 数据加载 ==========
    const loadData = async () => {
      try {
        const [rule, rewards, exchanges] = await Promise.all([
          ValueAddedServiceService.getBaseRule(),
          ValueAddedServiceService.getRewardServices(),
          ValueAddedServiceService.getExchangeServices()
        ])

        baseRule.value = rule
        rewardServices.value = rewards
        exchangeServices.value = exchanges

        // 初始化表单
        if (rule) {
          baseRuleForm.registerReward = rule.registerReward
          baseRuleForm.inviterReward = rule.inviterReward
          baseRuleForm.exchangeRate = rule.exchangeRate
          baseRuleForm.maxDeductionRatio = rule.maxDeductionRatio
          baseRuleForm.validityMonths = rule.validityMonths
          baseRuleForm.vip0 = rule.vipMultipliers['VIP0'] || 1.0
          baseRuleForm.vip1 = rule.vipMultipliers['VIP1'] || 1.2
          baseRuleForm.vip2 = rule.vipMultipliers['VIP2'] || 1.4
          baseRuleForm.vip3 = rule.vipMultipliers['VIP3'] || 1.6
          baseRuleForm.vip4 = rule.vipMultipliers['VIP4'] || 1.8
          baseRuleForm.vip5 = rule.vipMultipliers['VIP5'] || 2.0
          baseRuleForm.vip6 = rule.vipMultipliers['VIP6'] || 2.3
          baseRuleForm.vip7 = rule.vipMultipliers['VIP7'] || 2.6
          baseRuleForm.vip8 = rule.vipMultipliers['VIP8'] || 2.9
          baseRuleForm.vip9 = rule.vipMultipliers['VIP9'] || 3.2
        }
      } catch (error) {
        console.error('加载数据失败:', error)
      }
    }

    // ========== 基础规则操作 ==========
    const handleSaveBaseRule = async () => {
      if (!baseRule.value) return

      try {
        const vipMultipliers: Record<string, number> = {}
        for (let i = 0; i <= 9; i++) {
          vipMultipliers[`VIP${i}`] = baseRuleForm[`vip${i}` as keyof typeof baseRuleForm] as number
        }

        await ValueAddedServiceService.updateBaseRule(
          {
            registerReward: baseRuleForm.registerReward,
            inviterReward: baseRuleForm.inviterReward,
            exchangeRate: baseRuleForm.exchangeRate,
            maxDeductionRatio: baseRuleForm.maxDeductionRatio,
            validityMonths: baseRuleForm.validityMonths,
            vipMultipliers
          },
          '兔子'
        )

        isEditingBaseRule.value = false
        await loadData()
      } catch (error) {
        console.error('保存失败:', error)
      }
    }

    const handleCancelEditBaseRule = () => {
      if (!baseRule.value) return

      isEditingBaseRule.value = false
      baseRuleForm.registerReward = baseRule.value.registerReward
      baseRuleForm.inviterReward = baseRule.value.inviterReward
      baseRuleForm.exchangeRate = baseRule.value.exchangeRate
      baseRuleForm.maxDeductionRatio = baseRule.value.maxDeductionRatio
      baseRuleForm.validityMonths = baseRule.value.validityMonths
      baseRuleForm.vip0 = baseRule.value.vipMultipliers['VIP0'] || 1.0
      baseRuleForm.vip1 = baseRule.value.vipMultipliers['VIP1'] || 1.2
      baseRuleForm.vip2 = baseRule.value.vipMultipliers['VIP2'] || 1.4
      baseRuleForm.vip3 = baseRule.value.vipMultipliers['VIP3'] || 1.6
      baseRuleForm.vip4 = baseRule.value.vipMultipliers['VIP4'] || 1.8
      baseRuleForm.vip5 = baseRule.value.vipMultipliers['VIP5'] || 2.0
      baseRuleForm.vip6 = baseRule.value.vipMultipliers['VIP6'] || 2.3
      baseRuleForm.vip7 = baseRule.value.vipMultipliers['VIP7'] || 2.6
      baseRuleForm.vip8 = baseRule.value.vipMultipliers['VIP8'] || 2.9
      baseRuleForm.vip9 = baseRule.value.vipMultipliers['VIP9'] || 3.2
    }

    // ========== 奖励服务操作 ==========
    const handleEditReward = (item: PointsRewardItem) => {
      editingRewardItem.value = item
      isRewardEditDialogOpen.value = true
    }

    const handleDeleteReward = async (id: string) => {
      if (!confirm('确认删除该积分奖励服务？')) return

      try {
        await ValueAddedServiceService.deleteRewardService(id)
        await loadData()
      } catch (error) {
        console.error('删除失败:', error)
      }
    }

    const handleMoveReward = async (index: number, direction: 'up' | 'down') => {
      if (direction === 'up' && index === 0) return
      if (direction === 'down' && index === rewardServices.value.length - 1) return

      const newList = [...rewardServices.value]
      const targetIndex = direction === 'up' ? index - 1 : index + 1
      ;[newList[index], newList[targetIndex]] = [newList[targetIndex], newList[index]]

      const ids = newList.map(item => item.id)

      try {
        await ValueAddedServiceService.reorderRewardServices(ids)
        await loadData()
      } catch (error) {
        console.error('排序失败:', error)
      }
    }

    // ========== 换购服务操作 ==========
    const handleEditExchange = (item: PointsExchangeItem) => {
      editingExchangeItem.value = item
      isExchangeEditDialogOpen.value = true
    }

    const handleDeleteExchange = async (id: string) => {
      if (!confirm('确认删除该积分换购服务？')) return

      try {
        await ValueAddedServiceService.deleteExchangeService(id)
        await loadData()
      } catch (error) {
        console.error('删除失败:', error)
      }
    }

    const handleMoveExchange = async (index: number, direction: 'up' | 'down') => {
      if (direction === 'up' && index === 0) return
      if (direction === 'down' && index === exchangeServices.value.length - 1) return

      const newList = [...exchangeServices.value]
      const targetIndex = direction === 'up' ? index - 1 : index + 1
      ;[newList[index], newList[targetIndex]] = [newList[targetIndex], newList[index]]

      const ids = newList.map(item => item.id)

      try {
        await ValueAddedServiceService.reorderExchangeServices(ids)
        await loadData()
      } catch (error) {
        console.error('排序失败:', error)
      }
    }

    // ========== Dialog回调 ==========
    const handleDialogSuccess = async () => {
      await loadData()
    }

    // ========== 生命周期 ==========
    onMounted(() => {
      loadData()
    })

    return {
      // 数据
      baseRule,
      rewardServices,
      exchangeServices,

      // 基础规则
      isEditingBaseRule,
      baseRuleForm,
      handleSaveBaseRule,
      handleCancelEditBaseRule,

      // Dialog
      isRewardCreateDialogOpen,
      isRewardEditDialogOpen,
      editingRewardItem,
      isExchangeCreateDialogOpen,
      isExchangeEditDialogOpen,
      editingExchangeItem,

      // 表格
      rewardColumns,
      exchangeColumns,

      // 方法
      handleEditReward,
      handleDeleteReward,
      handleMoveReward,
      handleEditExchange,
      handleDeleteExchange,
      handleMoveExchange,
      handleDialogSuccess
    }
  }
})
</script>

<style scoped lang="less">
@import '@/styles/variables.less';

.page-container {
  padding: @spacing-xl;
  background: @bg-secondary;
  min-height: calc(100vh - 64px);
}

.card-style {
  margin-bottom: @spacing-xl;
  border-radius: @border-radius-lg;
  border: 1px solid @border-primary;
  box-shadow: @shadow-sm;
}

.card-title {
  font-size: @font-size-xl;
  font-weight: @font-weight-semibold;
  color: @text-primary;
}

.btn-style {
  height: @button-height;
  border-radius: @border-radius-base;
  background-color: @brand-primary;
  border-color: @brand-primary;
  transition: @transition-base;

  &:hover {
    background-color: @brand-primary-hover;
    border-color: @brand-primary-hover;
  }
}

.btn-style-outline {
  height: @button-height;
  border-radius: @border-radius-base;
  border-color: @border-secondary;
  transition: @transition-base;

  &:hover {
    border-color: @text-secondary;
  }
}

// 布局
.flex {
  display: flex;
}

.items-center {
  align-items: center;
}

.justify-between {
  justify-content: space-between;
}

.gap-2 > * + * {
  margin-left: @spacing-sm;
}

.mb-6 {
  margin-bottom: @spacing-xl;
}

.mb-3 {
  margin-bottom: @spacing-base;
}

.block {
  display: block;
}

// Grid布局
.grid-5 {
  display: grid;
  grid-template-columns: repeat(5, 1fr);
  gap: @spacing-xl;
}

.grid-10 {
  display: grid;
  grid-template-columns: repeat(10, 1fr);
  gap: @spacing-base;
}

// 字段样式
.field-item {
  label {
    display: block;
    font-size: @font-size-base;
    font-weight: @font-weight-medium;
    color: @text-secondary;
    margin-bottom: @spacing-sm;
  }
}

.input-with-unit {
  display: flex;
  align-items: center;
  gap: @spacing-xs;

  .input-style {
    flex: 1;
    height: @input-height-lg;
    border-radius: @border-radius-base;
  }

  .unit-text {
    font-size: @font-size-xs;
    color: @text-secondary;
    white-space: nowrap;
  }
}

.value-display {
  height: @input-height-lg;
  display: flex;
  align-items: center;

  span {
    font-weight: @font-weight-normal;
    color: @text-primary;
    font-size: @font-size-base;
  }
}

// VIP倍数
.vip-multipliers {
  padding-top: @spacing-base;
  border-top: 1px solid @border-primary;

  label {
    font-size: @font-size-base;
    font-weight: @font-weight-medium;
    color: @text-secondary;
  }
}

.vip-item {
  .vip-label {
    font-size: @font-size-xs;
    color: @text-secondary;
    text-align: center;
    margin-bottom: 6px;
  }

  .vip-input {
    width: 100%;
    height: @button-height;
    border-radius: @border-radius-base;
    font-size: @font-size-xs;
    text-align: center;
  }

  .vip-value {
    height: @button-height;
    display: flex;
    align-items: center;
    justify-content: center;

    span {
      font-weight: @font-weight-normal;
      color: @text-primary;
      font-size: @font-size-base;
    }
  }
}

// 表格样式
.table-wrapper {
  border: 1px solid @border-primary;
  border-radius: @border-radius-lg;
  overflow: hidden;

  :deep(.ant-table) {
    font-size: @font-size-base;

    .ant-table-thead > tr > th {
      background: @bg-secondary;
      color: @text-primary;
      font-weight: @font-weight-semibold;
      padding: @spacing-base @spacing-md;
      border-bottom: 1px solid @border-primary;
    }

    .ant-table-tbody > tr {
      transition: @transition-fast;

      &:hover {
        background: @bg-hover;
      }

      > td {
        padding: @spacing-base @spacing-md;
        color: @text-primary;
        border-bottom: 1px solid @border-primary;
      }
    }
  }
}

.action-buttons {
  display: flex;
  align-items: center;
  justify-content: center;
  gap: @spacing-sm;

  .ant-btn {
    border-radius: @border-radius-base;
    transition: @transition-base;
  }
}

.btn-delete {
  border-color: @error-color;
  color: @error-color;

  &:hover {
    background-color: fade(@error-color, 10%);
    border-color: @error-color;
    color: @error-color;
  }
}

// 颜色类
.text-green-600 {
  color: @success-color;
  font-weight: @font-weight-normal;
}

.text-red-600 {
  color: @error-color;
  font-weight: @font-weight-normal;
}

.font-medium {
  font-weight: @font-weight-medium;
  color: @text-primary;
}

.font-semibold {
  font-weight: @font-weight-semibold;
  color: @text-primary;
}
</style>

// app/pages/PlatformAdmin/PointsManagement/PointsConfigPage.tsx
/**
 * 平台后台 - 积分管理配置页面（3个Card：基础规则、奖励服务、换购服务）
 */

import { useState } from 'react'
import { Form } from '@remix-run/react'
import type { PointsBaseRule, PointsRewardItem, PointsExchangeItem } from './types/valueAddedService.types'
import { Card, CardContent, CardHeader, CardTitle } from '~/components/ui/card'
import { Button } from '~/components/ui/button'
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '~/components/ui/table'
import { Input } from '~/components/ui/input'
import { Plus, Edit, Trash2, ChevronUp, ChevronDown } from 'lucide-react'
import MainLayout from '~/pages/PointsSystem/components/MainLayout'
import ServiceItemDialog from './components/ServiceItemDialog'

interface PointsConfigPageProps {
  baseRule: PointsBaseRule
  rewardServices: PointsRewardItem[]
  exchangeServices: PointsExchangeItem[]
  error: string | null
}

export default function PointsConfigPage({
  baseRule,
  rewardServices,
  exchangeServices,
  error,
}: PointsConfigPageProps) {
  // 基础规则编辑状态
  const [isEditingBaseRule, setIsEditingBaseRule] = useState(false)
  const [baseRuleForm, setBaseRuleForm] = useState({
    registerReward: baseRule.registerReward,
    inviterReward: baseRule.inviterReward,
    exchangeRate: baseRule.exchangeRate,
    maxDeductionRatio: baseRule.maxDeductionRatio,
    validityMonths: baseRule.validityMonths,
    vip0: baseRule.vipMultipliers['VIP0'] || 1.0,
    vip1: baseRule.vipMultipliers['VIP1'] || 1.2,
    vip2: baseRule.vipMultipliers['VIP2'] || 1.4,
    vip3: baseRule.vipMultipliers['VIP3'] || 1.6,
    vip4: baseRule.vipMultipliers['VIP4'] || 1.8,
    vip5: baseRule.vipMultipliers['VIP5'] || 2.0,
    vip6: baseRule.vipMultipliers['VIP6'] || 2.3,
    vip7: baseRule.vipMultipliers['VIP7'] || 2.6,
    vip8: baseRule.vipMultipliers['VIP8'] || 2.9,
    vip9: baseRule.vipMultipliers['VIP9'] || 3.2,
  })

  // 服务Dialog状态
  const [isRewardCreateDialogOpen, setIsRewardCreateDialogOpen] = useState(false)
  const [isRewardEditDialogOpen, setIsRewardEditDialogOpen] = useState(false)
  const [editingRewardItem, setEditingRewardItem] = useState<PointsRewardItem | null>(null)

  const [isExchangeCreateDialogOpen, setIsExchangeCreateDialogOpen] = useState(false)
  const [isExchangeEditDialogOpen, setIsExchangeEditDialogOpen] = useState(false)
  const [editingExchangeItem, setEditingExchangeItem] = useState<PointsExchangeItem | null>(null)

  // 编辑奖励
  const handleEditReward = (item: PointsRewardItem) => {
    setEditingRewardItem(item)
    setIsRewardEditDialogOpen(true)
  }

  // 编辑换购
  const handleEditExchange = (item: PointsExchangeItem) => {
    setEditingExchangeItem(item)
    setIsExchangeEditDialogOpen(true)
  }

  // 删除奖励
  const handleDeleteReward = (id: string) => {
    if (confirm('确认删除该积分奖励服务？')) {
      document.getElementById(`delete-reward-${id}`)?.dispatchEvent(
        new Event('submit', { bubbles: true, cancelable: true })
      )
    }
  }

  // 删除换购
  const handleDeleteExchange = (id: string) => {
    if (confirm('确认删除该积分换购服务？')) {
      document.getElementById(`delete-exchange-${id}`)?.dispatchEvent(
        new Event('submit', { bubbles: true, cancelable: true })
      )
    }
  }

  // 上移/下移 - 奖励
  const handleMoveReward = (index: number, direction: 'up' | 'down') => {
    if (direction === 'up' && index === 0) return
    if (direction === 'down' && index === rewardServices.length - 1) return

    const newList = [...rewardServices]
    const targetIndex = direction === 'up' ? index - 1 : index + 1
    ;[newList[index], newList[targetIndex]] = [newList[targetIndex], newList[index]]

    const ids = newList.map((item) => item.id)
    const form = document.getElementById('reorder-reward-form') as HTMLFormElement
    if (form) {
      const input = form.querySelector('input[name="ids"]') as HTMLInputElement
      if (input) {
        input.value = JSON.stringify(ids)
        form.requestSubmit()
      }
    }
  }

  // 上移/下移 - 换购
  const handleMoveExchange = (index: number, direction: 'up' | 'down') => {
    if (direction === 'up' && index === 0) return
    if (direction === 'down' && index === exchangeServices.length - 1) return

    const newList = [...exchangeServices]
    const targetIndex = direction === 'up' ? index - 1 : index + 1
    ;[newList[index], newList[targetIndex]] = [newList[targetIndex], newList[index]]

    const ids = newList.map((item) => item.id)
    const form = document.getElementById('reorder-exchange-form') as HTMLFormElement
    if (form) {
      const input = form.querySelector('input[name="ids"]') as HTMLInputElement
      if (input) {
        input.value = JSON.stringify(ids)
        form.requestSubmit()
      }
    }
  }

  if (error) {
    return (
      <MainLayout>
        <div className="p-6">
          <div className="bg-red-50 border border-red-200 text-red-700 px-4 py-3 rounded-lg">
            错误: {error}
          </div>
        </div>
      </MainLayout>
    )
  }

  return (
    <MainLayout>
      <div className="p-6 space-y-6 overflow-y-auto h-full">
        {/* 服务Dialog */}
        <ServiceItemDialog
          open={isRewardCreateDialogOpen}
          onOpenChange={setIsRewardCreateDialogOpen}
          mode="create"
          type="reward"
        />
        <ServiceItemDialog
          open={isRewardEditDialogOpen}
          onOpenChange={setIsRewardEditDialogOpen}
          mode="edit"
          type="reward"
          item={editingRewardItem}
        />
        <ServiceItemDialog
          open={isExchangeCreateDialogOpen}
          onOpenChange={setIsExchangeCreateDialogOpen}
          mode="create"
          type="exchange"
        />
        <ServiceItemDialog
          open={isExchangeEditDialogOpen}
          onOpenChange={setIsExchangeEditDialogOpen}
          mode="edit"
          type="exchange"
          item={editingExchangeItem}
        />

        {/* 隐藏的重排序表单 */}
        <Form method="post" action="/platform-admin/points-management/config" id="reorder-reward-form" style={{ display: 'none' }}>
          <input type="hidden" name="action" value="reorder-reward" />
          <input type="hidden" name="ids" value="[]" />
        </Form>
        <Form method="post" action="/platform-admin/points-management/config" id="reorder-exchange-form" style={{ display: 'none' }}>
          <input type="hidden" name="action" value="reorder-exchange" />
          <input type="hidden" name="ids" value="[]" />
        </Form>

        {/* Card 1: 基础规则配置 */}
        <Card className="rounded-xl border-slate-200 bg-white shadow-sm">
          <CardHeader className="flex flex-row items-center justify-between">
            <CardTitle className="text-lg font-semibold text-slate-900">积分基础规则</CardTitle>
            {!isEditingBaseRule ? (
              <Button
                onClick={() => setIsEditingBaseRule(true)}
                className="h-9 bg-blue-600 hover:bg-blue-700"
              >
                编辑
              </Button>
            ) : (
              <div className="flex gap-2">
                <Button
                  type="submit"
                  form="base-rule-form"
                  className="h-9 bg-blue-600 hover:bg-blue-700"
                >
                  保存
                </Button>
                <Button
                  type="button"
                  variant="outline"
                  className="h-9 border-slate-300"
                  onClick={() => {
                    setIsEditingBaseRule(false)
                    setBaseRuleForm({
                      registerReward: baseRule.registerReward,
                      inviterReward: baseRule.inviterReward,
                      exchangeRate: baseRule.exchangeRate,
                      maxDeductionRatio: baseRule.maxDeductionRatio,
                      validityMonths: baseRule.validityMonths,
                      vip0: baseRule.vipMultipliers['VIP0'] || 1.0,
                      vip1: baseRule.vipMultipliers['VIP1'] || 1.2,
                      vip2: baseRule.vipMultipliers['VIP2'] || 1.4,
                      vip3: baseRule.vipMultipliers['VIP3'] || 1.6,
                      vip4: baseRule.vipMultipliers['VIP4'] || 1.8,
                      vip5: baseRule.vipMultipliers['VIP5'] || 2.0,
                      vip6: baseRule.vipMultipliers['VIP6'] || 2.3,
                      vip7: baseRule.vipMultipliers['VIP7'] || 2.6,
                      vip8: baseRule.vipMultipliers['VIP8'] || 2.9,
                      vip9: baseRule.vipMultipliers['VIP9'] || 3.2,
                    })
                  }}
                >
                  取消
                </Button>
              </div>
            )}
          </CardHeader>
          <CardContent>
            <Form method="post" action="/platform-admin/points-management/config" className="space-y-6" id="base-rule-form">
              <input type="hidden" name="action" value="update-base-rule" />

              {/* 第一行：5个基础配置 */}
              <div className="grid grid-cols-5 gap-6">
                <div className="space-y-2">
                  <label className="text-sm font-medium text-slate-600">注册奖励</label>
                  {isEditingBaseRule ? (
                    <div className="flex items-center gap-1">
                      <Input
                        type="number"
                        name="registerReward"
                        value={baseRuleForm.registerReward}
                        onChange={(e) => setBaseRuleForm({ ...baseRuleForm, registerReward: parseInt(e.target.value) || 0 })}
                        className="h-9 flex-1 border-slate-300 focus:border-blue-500 focus:ring-2 focus:ring-blue-500/20"
                        min="0"
                      />
                      <span className="text-xs text-slate-600 whitespace-nowrap">积分</span>
                    </div>
                  ) : (
                    <div className="h-9 flex items-center">
                      <span className="font-semibold text-slate-900 text-sm">{baseRule.registerReward}积分</span>
                    </div>
                  )}
                </div>

                <div className="space-y-2">
                  <label className="text-sm font-medium text-slate-600">邀请人奖励</label>
                  {isEditingBaseRule ? (
                    <div className="flex items-center gap-1">
                      <Input
                        type="number"
                        name="inviterReward"
                        value={baseRuleForm.inviterReward}
                        onChange={(e) => setBaseRuleForm({ ...baseRuleForm, inviterReward: parseInt(e.target.value) || 0 })}
                        className="h-9 flex-1 border-slate-300 focus:border-blue-500 focus:ring-2 focus:ring-blue-500/20"
                        min="0"
                      />
                      <span className="text-xs text-slate-600 whitespace-nowrap">积分</span>
                    </div>
                  ) : (
                    <div className="h-9 flex items-center">
                      <span className="font-semibold text-slate-900 text-sm">{baseRule.inviterReward}积分</span>
                    </div>
                  )}
                </div>

                <div className="space-y-2">
                  <label className="text-sm font-medium text-slate-600">积分兑换汇率</label>
                  {isEditingBaseRule ? (
                    <div className="flex items-center gap-1">
                      <Input
                        type="number"
                        name="exchangeRate"
                        value={baseRuleForm.exchangeRate}
                        onChange={(e) => setBaseRuleForm({ ...baseRuleForm, exchangeRate: parseInt(e.target.value) || 0 })}
                        className="h-9 flex-1 border-slate-300 focus:border-blue-500 focus:ring-2 focus:ring-blue-500/20"
                        min="1"
                      />
                      <span className="text-xs text-slate-600 whitespace-nowrap">积分=1元</span>
                    </div>
                  ) : (
                    <div className="h-9 flex items-center">
                      <span className="font-semibold text-slate-900 text-sm">{baseRule.exchangeRate}积分=1元</span>
                    </div>
                  )}
                </div>

                <div className="space-y-2">
                  <label className="text-sm font-medium text-slate-600">最大抵扣比例</label>
                  {isEditingBaseRule ? (
                    <div className="flex items-center gap-1">
                      <Input
                        type="number"
                        name="maxDeductionRatio"
                        value={baseRuleForm.maxDeductionRatio}
                        onChange={(e) => setBaseRuleForm({ ...baseRuleForm, maxDeductionRatio: parseInt(e.target.value) || 0 })}
                        className="h-9 flex-1 border-slate-300 focus:border-blue-500 focus:ring-2 focus:ring-blue-500/20"
                        min="0"
                        max="100"
                      />
                      <span className="text-xs text-slate-600">%</span>
                    </div>
                  ) : (
                    <div className="h-9 flex items-center">
                      <span className="font-semibold text-slate-900 text-sm">{baseRule.maxDeductionRatio}%</span>
                    </div>
                  )}
                </div>

                <div className="space-y-2">
                  <label className="text-sm font-medium text-slate-600">积分有效期</label>
                  {isEditingBaseRule ? (
                    <div className="flex items-center gap-1">
                      <Input
                        type="number"
                        name="validityMonths"
                        value={baseRuleForm.validityMonths}
                        onChange={(e) => setBaseRuleForm({ ...baseRuleForm, validityMonths: parseInt(e.target.value) || 0 })}
                        className="h-9 flex-1 border-slate-300 focus:border-blue-500 focus:ring-2 focus:ring-blue-500/20"
                        min="1"
                      />
                      <span className="text-xs text-slate-600">月</span>
                    </div>
                  ) : (
                    <div className="h-9 flex items-center">
                      <span className="font-semibold text-slate-900 text-sm">{baseRule.validityMonths}个月</span>
                    </div>
                  )}
                </div>
              </div>

              {/* 第二行：入住返还倍数 */}
              <div className="space-y-3 pt-3 border-t border-slate-200">
                <label className="text-sm font-medium text-slate-600">入住返还倍数</label>
                <div className="grid grid-cols-10 gap-3">
                  {['vip0', 'vip1', 'vip2', 'vip3', 'vip4', 'vip5', 'vip6', 'vip7', 'vip8', 'vip9'].map((key, idx) => (
                    <div key={key} className="space-y-1.5">
                      <div className="text-xs text-slate-600 text-center">VIP{idx}</div>
                      {isEditingBaseRule ? (
                        <Input
                          type="number"
                          name={key}
                          value={baseRuleForm[key as keyof typeof baseRuleForm]}
                          onChange={(e) => setBaseRuleForm({ ...baseRuleForm, [key]: parseFloat(e.target.value) || 1.0 })}
                          className="h-8 text-xs text-center border-slate-300 focus:border-blue-500 focus:ring-1 focus:ring-blue-500/20"
                          step="0.1"
                          min="1"
                        />
                      ) : (
                        <div className="h-8 flex items-center justify-center">
                          <span className="font-semibold text-slate-900 text-sm">{baseRule.vipMultipliers[`VIP${idx}`]?.toFixed(1)}</span>
                        </div>
                      )}
                    </div>
                  ))}
                </div>
              </div>
            </Form>
          </CardContent>
        </Card>

        {/* Card 2: 积分奖励服务 */}
        <Card className="rounded-xl border-slate-200 bg-white shadow-sm">
          <CardHeader className="flex flex-row items-center justify-between">
            <CardTitle className="text-lg font-semibold text-slate-900">积分奖励服务</CardTitle>
            <Button
              onClick={() => setIsRewardCreateDialogOpen(true)}
              className="h-9 bg-blue-600 hover:bg-blue-700"
            >
              <Plus className="w-4 h-4 mr-2" />
              新增
            </Button>
          </CardHeader>
          <CardContent>
            <div className="border border-slate-200 rounded-lg overflow-hidden">
              <Table>
                <TableHeader>
                  <TableRow className="border-slate-200 bg-slate-50">
                    <TableHead className="text-slate-900 font-semibold w-[80px]">序号</TableHead>
                    <TableHead className="text-slate-900 font-semibold">服务内容</TableHead>
                    <TableHead className="text-slate-900 font-semibold w-[120px]">奖励积分</TableHead>
                    <TableHead className="text-slate-900 font-semibold text-center w-[280px]">操作</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {rewardServices.length === 0 ? (
                    <TableRow>
                      <TableCell colSpan={4} className="text-center text-slate-500 py-8">
                        暂无数据
                      </TableCell>
                    </TableRow>
                  ) : (
                    rewardServices.map((item, index) => (
                      <TableRow key={item.id} className="hover:bg-slate-50 transition-colors">
                        <TableCell className="text-slate-900">{item.序号}</TableCell>
                        <TableCell className="text-slate-900 font-medium">{item.serviceName}</TableCell>
                        <TableCell className="text-green-600 font-semibold">+{item.pointsReward}</TableCell>
                        <TableCell>
                          <div className="flex items-center justify-center gap-2">
                            <Button
                              variant="outline"
                              size="sm"
                              className="h-7 px-2 border-slate-300"
                              disabled={index === 0}
                              onClick={() => handleMoveReward(index, 'up')}
                            >
                              <ChevronUp className="w-4 h-4" />
                            </Button>

                            <Button
                              variant="outline"
                              size="sm"
                              className="h-7 px-2 border-slate-300"
                              disabled={index === rewardServices.length - 1}
                              onClick={() => handleMoveReward(index, 'down')}
                            >
                              <ChevronDown className="w-4 h-4" />
                            </Button>

                            <Button
                              variant="outline"
                              size="sm"
                              className="h-7 px-3 border-slate-300"
                              onClick={() => handleEditReward(item)}
                            >
                              <Edit className="w-3 h-3 mr-1" />
                              编辑
                            </Button>

                            <Form
                              method="post"
                              action="/platform-admin/points-management/config"
                              id={`delete-reward-${item.id}`}
                            >
                              <input type="hidden" name="action" value="delete-reward" />
                              <input type="hidden" name="id" value={item.id} />
                              <Button
                                type="button"
                                variant="outline"
                                size="sm"
                                className="h-7 px-3 border-red-300 text-red-700 hover:bg-red-50"
                                onClick={() => handleDeleteReward(item.id)}
                              >
                                <Trash2 className="w-3 h-3 mr-1" />
                                删除
                              </Button>
                            </Form>
                          </div>
                        </TableCell>
                      </TableRow>
                    ))
                  )}
                </TableBody>
              </Table>
            </div>
          </CardContent>
        </Card>

        {/* Card 3: 积分换购服务 */}
        <Card className="rounded-xl border-slate-200 bg-white shadow-sm">
          <CardHeader className="flex flex-row items-center justify-between">
            <CardTitle className="text-lg font-semibold text-slate-900">积分换购服务</CardTitle>
            <Button
              onClick={() => setIsExchangeCreateDialogOpen(true)}
              className="h-9 bg-blue-600 hover:bg-blue-700"
            >
              <Plus className="w-4 h-4 mr-2" />
              新增
            </Button>
          </CardHeader>
          <CardContent>
            <div className="border border-slate-200 rounded-lg overflow-hidden">
              <Table>
                <TableHeader>
                  <TableRow className="border-slate-200 bg-slate-50">
                    <TableHead className="text-slate-900 font-semibold w-[80px]">序号</TableHead>
                    <TableHead className="text-slate-900 font-semibold">服务内容</TableHead>
                    <TableHead className="text-slate-900 font-semibold w-[120px]">消耗积分</TableHead>
                    <TableHead className="text-slate-900 font-semibold text-center w-[340px]">操作</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {exchangeServices.length === 0 ? (
                    <TableRow>
                      <TableCell colSpan={4} className="text-center text-slate-500 py-8">
                        暂无数据
                      </TableCell>
                    </TableRow>
                  ) : (
                    exchangeServices.map((item, index) => (
                      <TableRow key={item.id} className="hover:bg-slate-50 transition-colors">
                        <TableCell className="text-slate-900">{item.序号}</TableCell>
                        <TableCell className="text-slate-900 font-medium">{item.serviceName}</TableCell>
                        <TableCell className="text-red-600 font-semibold">-{Math.abs(item.pointsCost)}</TableCell>
                        <TableCell>
                          <div className="flex items-center justify-center gap-2">
                            <Button
                              variant="outline"
                              size="sm"
                              className="h-7 px-2 border-slate-300"
                              disabled={index === 0}
                              onClick={() => handleMoveExchange(index, 'up')}
                            >
                              <ChevronUp className="w-4 h-4" />
                            </Button>

                            <Button
                              variant="outline"
                              size="sm"
                              className="h-7 px-2 border-slate-300"
                              disabled={index === exchangeServices.length - 1}
                              onClick={() => handleMoveExchange(index, 'down')}
                            >
                              <ChevronDown className="w-4 h-4" />
                            </Button>

                            <Button
                              variant="outline"
                              size="sm"
                              className="h-7 px-3 border-slate-300"
                              onClick={() => handleEditExchange(item)}
                            >
                              <Edit className="w-3 h-3 mr-1" />
                              编辑
                            </Button>

                            <Form
                              method="post"
                              action="/platform-admin/points-management/config"
                              id={`delete-exchange-${item.id}`}
                            >
                              <input type="hidden" name="action" value="delete-exchange" />
                              <input type="hidden" name="id" value={item.id} />
                              <Button
                                type="button"
                                variant="outline"
                                size="sm"
                                className="h-7 px-3 border-red-300 text-red-700 hover:bg-red-50"
                                onClick={() => handleDeleteExchange(item.id)}
                              >
                                <Trash2 className="w-3 h-3 mr-1" />
                                删除
                              </Button>
                            </Form>
                          </div>
                        </TableCell>
                      </TableRow>
                    ))
                  )}
                </TableBody>
              </Table>
            </div>
          </CardContent>
        </Card>
      </div>
    </MainLayout>
  )
}
