// app/pages/PlatformAdmin/CouponManagement/CouponListPage.tsx
/**
 * 平台后台 - 优惠券列表页面
 */

import { useState } from 'react'
import { Form, Link } from '@remix-run/react'
import type { Coupon } from './types/coupon.types'
import { Card, CardContent, CardHeader, CardTitle } from '~/components/ui/card'
import { Button } from '~/components/ui/button'
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '~/components/ui/table'
import { Badge } from '~/components/ui/badge'
import { Pagination, PaginationContent, PaginationItem, PaginationLink, PaginationNext, PaginationPrevious } from '~/components/ui/pagination'
import { Plus, Edit, History } from 'lucide-react'
import MainLayout from '~/pages/PointsSystem/components/MainLayout'
import CouponDialog from './components/CouponDialog'

interface CouponListPageProps {
  coupons: Coupon[]
  total: number
  page: number
  pageSize: number
  totalPages: number
  error: string | null
}

/**
 * 获取优惠券类型文本
 */
function getCouponTypeText(type: string): string {
  const map: Record<string, string> = {
    full_reduction: '满减券',
    discount: '折扣券',
    instant_reduction: '立减券',
  }
  return map[type] || type
}

/**
 * 获取优惠券类型颜色样式
 */
function getCouponTypeBadgeClass(type: string): string {
  const classMap: Record<string, string> = {
    full_reduction: 'bg-orange-50 text-orange-700 border-orange-300',
    discount: 'bg-green-50 text-green-700 border-green-300',
    instant_reduction: 'bg-blue-50 text-blue-700 border-blue-300',
  }
  return classMap[type] || 'border-slate-300 text-slate-700'
}

/**
 * 获取有效期描述
 */
function getValidDaysText(days: number): string {
  if (days === 0) return '永久'
  return `发放后${days}天`
}

export default function CouponListPage({ coupons, total, page, pageSize, totalPages, error }: CouponListPageProps) {
  // Dialog弹窗状态
  const [isCreateDialogOpen, setIsCreateDialogOpen] = useState(false)
  const [isEditDialogOpen, setIsEditDialogOpen] = useState(false)
  const [editingCoupon, setEditingCoupon] = useState<Coupon | null>(null)

  // 打开编辑Dialog
  const handleEdit = (coupon: Coupon) => {
    setEditingCoupon(coupon)
    setIsEditDialogOpen(true)
  }

  if (error) {
    return (
      <MainLayout>
        <div className="p-6">
          <div className="bg-red-50 border border-red-200 text-red-700 px-4 py-3 rounded-lg">
            错误: {error}
          </div>
        </div>
      </MainLayout>
    )
  }

  return (
    <MainLayout>
      <div className="p-6 space-y-6">
      {/* 创建优惠券Dialog */}
      <CouponDialog
        open={isCreateDialogOpen}
        onOpenChange={setIsCreateDialogOpen}
        mode="create"
      />

      {/* 编辑优惠券Dialog */}
      <CouponDialog
        open={isEditDialogOpen}
        onOpenChange={setIsEditDialogOpen}
        mode="edit"
        coupon={editingCoupon}
      />

      {/* 优惠券列表 */}
      <Card className="rounded-xl border-slate-200 bg-white shadow-sm">
        <CardHeader className="flex flex-row items-center justify-between">
          <CardTitle className="text-lg font-semibold text-slate-900">优惠券列表</CardTitle>
          <div className="flex items-center gap-2">
            <Link to="/platform-admin/coupon-management/operation-logs">
              <Button variant="outline" className="h-9">
                <History className="w-4 h-4 mr-2" />
                操作记录
              </Button>
            </Link>
            <Button
              onClick={() => setIsCreateDialogOpen(true)}
              className="h-9 bg-blue-600 hover:bg-blue-700"
            >
              <Plus className="w-4 h-4 mr-2" />
              创建优惠券
            </Button>
          </div>
        </CardHeader>
        <CardContent>
          <div className="border border-slate-200 rounded-lg overflow-hidden">
            <Table>
              <TableHeader>
                <TableRow className="border-slate-200 bg-slate-50">
                  <TableHead className="text-slate-900 font-semibold">优惠券ID</TableHead>
                  <TableHead className="text-slate-900 font-semibold">优惠券类型</TableHead>
                  <TableHead className="text-slate-900 font-semibold">优惠券名称</TableHead>
                  <TableHead className="text-slate-900 font-semibold">备注说明</TableHead>
                  <TableHead className="text-slate-900 font-semibold">有效期</TableHead>
                  <TableHead className="text-slate-900 font-semibold">费用承担</TableHead>
                  <TableHead className="text-slate-900 font-semibold text-center">短信通知</TableHead>
                  <TableHead className="text-slate-900 font-semibold">创建时间</TableHead>
                  <TableHead className="text-slate-900 font-semibold">创建人</TableHead>
                  <TableHead className="text-slate-900 font-semibold text-center">操作</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {coupons.length === 0 ? (
                  <TableRow>
                    <TableCell colSpan={10} className="text-center text-slate-500 py-8">
                      暂无数据
                    </TableCell>
                  </TableRow>
                ) : (
                  coupons.map((coupon) => (
                    <TableRow key={coupon.id} className="hover:bg-slate-50 transition-colors">
                      <TableCell className="text-slate-900 font-medium">{coupon.id}</TableCell>
                      <TableCell>
                        <Badge className={`${getCouponTypeBadgeClass(coupon.type)} border`}>
                          {getCouponTypeText(coupon.type)}
                        </Badge>
                      </TableCell>
                      <TableCell className="text-slate-900">{coupon.name}</TableCell>
                      <TableCell className="text-slate-900 text-sm max-w-[150px] truncate" title={coupon.remark || '-'}>
                        {coupon.remark || '-'}
                      </TableCell>
                      <TableCell className="text-slate-900 text-sm">
                        {getValidDaysText(coupon.validDays)}
                      </TableCell>
                      <TableCell className="text-slate-900 text-sm">
                        平台{coupon.platformRatio}% / 商户{coupon.merchantRatio}%
                      </TableCell>
                      <TableCell className="text-center">
                        <span className={coupon.smsNotify ? "text-green-700" : "text-slate-600"}>
                          {coupon.smsNotify ? '是' : '否'}
                        </span>
                      </TableCell>
                      <TableCell className="text-slate-900 text-sm">{coupon.createdAt}</TableCell>
                      <TableCell className="text-slate-900 text-sm">{coupon.createdBy}</TableCell>
                      <TableCell>
                        <div className="flex items-center justify-center gap-2">
                          {/* 编辑按钮 */}
                          <Button
                            variant="outline"
                            size="sm"
                            className="h-7 px-3 border-slate-300"
                            onClick={() => handleEdit(coupon)}
                          >
                            <Edit className="w-3 h-3 mr-1" />
                            编辑
                          </Button>

                          {/* 启用/停用按钮 */}
                          <Form method="post" action={`/platform-admin/coupon-management/toggle/${coupon.id}`}>
                            <Button
                              type="submit"
                              variant="outline"
                              size="sm"
                              className={`h-7 px-3 ${
                                coupon.status === 'enabled'
                                  ? 'border-orange-300 text-orange-700 hover:bg-orange-50'
                                  : 'border-green-300 text-green-700 hover:bg-green-50'
                              }`}
                            >
                              {coupon.status === 'enabled' ? '停用' : '启用'}
                            </Button>
                          </Form>
                        </div>
                      </TableCell>
                    </TableRow>
                  ))
                )}
              </TableBody>
            </Table>
          </div>

          {/* 分页组件 */}
          {totalPages > 1 && (
            <div className="flex items-center justify-between px-4 py-4 border-t border-slate-200">
              <div className="text-sm text-slate-600 whitespace-nowrap">
                共 {total} 条
              </div>
              <Pagination>
                <PaginationContent>
                  <PaginationItem>
                    <PaginationPrevious
                      href={page > 1 ? `?page=${page - 1}` : '#'}
                      className={page === 1 ? 'pointer-events-none opacity-50' : ''}
                    />
                  </PaginationItem>

                  {/* 页码列表 */}
                  {Array.from({ length: Math.min(7, totalPages) }, (_, i) => {
                    let pageNum
                    if (totalPages <= 7) {
                      pageNum = i + 1
                    } else if (page <= 4) {
                      pageNum = i + 1
                    } else if (page >= totalPages - 3) {
                      pageNum = totalPages - 6 + i
                    } else {
                      pageNum = page - 3 + i
                    }

                    return (
                      <PaginationItem key={pageNum}>
                        <PaginationLink
                          href={`?page=${pageNum}`}
                          isActive={pageNum === page}
                        >
                          {pageNum}
                        </PaginationLink>
                      </PaginationItem>
                    )
                  })}

                  <PaginationItem>
                    <PaginationNext
                      href={page < totalPages ? `?page=${page + 1}` : '#'}
                      className={page === totalPages ? 'pointer-events-none opacity-50' : ''}
                    />
                  </PaginationItem>
                </PaginationContent>
              </Pagination>
            </div>
          )}
        </CardContent>
      </Card>
      </div>
    </MainLayout>
  )
}

// src/views/PlatformAdmin/CouponManagement/CouponListPage.vue
<template>
  <sidebar>
    <div class="coupon-list-page">
      <!-- 创建优惠券Dialog -->
      <coupon-dialog
        :visible="isCreateDialogOpen"
        mode="create"
        @close="isCreateDialogOpen = false"
        @success="handleDialogSuccess"
      />

      <!-- 编辑优惠券Dialog -->
      <coupon-dialog
        :visible="isEditDialogOpen"
        mode="edit"
        :coupon="editingCoupon"
        @close="isEditDialogOpen = false"
        @success="handleDialogSuccess"
      />

      <!-- 优惠券列表 -->
      <a-card :bordered="false" class="list-card">
        <div slot="title" class="card-header">
          <span class="card-title">优惠券列表</span>
          <div class="header-actions">
            <a-button @click="goToOperationLogs">
              <a-icon type="history" />
              操作记录
            </a-button>
            <a-button type="primary" @click="isCreateDialogOpen = true">
              <a-icon type="plus" />
              创建优惠券
            </a-button>
          </div>
        </div>

        <a-table
          :columns="columns"
          :data-source="coupons"
          :pagination="paginationConfig"
          :loading="loading"
          :scroll="{ x: 1300 }"
          row-key="id"
          class="custom-table"
          @change="handleTableChange"
        >
          <!-- 优惠券ID -->
          <template slot="id" slot-scope="id">
            <span class="id-text">{{ id }}</span>
          </template>

          <!-- 优惠券类型 -->
          <template slot="type" slot-scope="type">
            <a-tag :class="getCouponTypeBadgeClass(type)">
              {{ getCouponTypeText(type) }}
            </a-tag>
          </template>

          <!-- 优惠券名称 -->
          <template slot="name" slot-scope="name">
            <span class="name-text">{{ name }}</span>
          </template>

          <!-- 优惠内容 -->
          <template slot="content" slot-scope="text, record">
            <div class="content-text">{{ getCouponContent(record) }}</div>
          </template>

          <!-- 备注说明 -->
          <template slot="remark" slot-scope="remark">
            <span class="remark-text" :title="remark || '—'">
              {{ remark || '—' }}
            </span>
          </template>

          <!-- 有效天数 -->
          <template slot="validDays" slot-scope="text, record">
            <span class="valid-text">{{ getValidDaysText(record) }}</span>
          </template>

          <!-- 有效日期 -->
          <template slot="validDateRange" slot-scope="text, record">
            <div v-if="record.validDateRange && record.validDateRange.length === 2" class="date-range-cell">
              <div class="date-line">{{ record.validDateRange[0] }}</div>
              <div class="date-line">{{ record.validDateRange[1] }}</div>
            </div>
            <span v-else class="valid-text">—</span>
          </template>

          <!-- 费用承担 -->
          <template slot="ratio" slot-scope="text, record">
            <div class="ratio-text">
              <div>平台 {{ record.platformRatio }}%</div>
              <div class="ratio-merchant">商户 {{ record.merchantRatio }}%</div>
            </div>
          </template>

          <!-- 创建时间 -->
          <template slot="createdAt" slot-scope="createdAt">
            <div class="datetime-cell">
              <div class="date">{{ formatDate(createdAt) }}</div>
              <div class="time">{{ formatTime(createdAt) }}</div>
            </div>
          </template>

          <!-- 操作 -->
          <template slot="action" slot-scope="text, record">
            <div class="action-btns">
              <a-button size="small" @click="handleEdit(record)">
                <a-icon type="edit" />
                编辑
              </a-button>
              <a-button
                size="small"
                :type="record.status === 'enabled' ? 'danger' : 'primary'"
                @click="handleToggleStatus(record)"
              >
                {{ record.status === 'enabled' ? '停用' : '启用' }}
              </a-button>
            </div>
          </template>
        </a-table>
      </a-card>
    </div>
  </sidebar>
</template>

<script>
import { defineComponent, ref, reactive, onMounted } from '@vue/composition-api'
import Sidebar from '@/components/Layout/Sidebar.vue'
import CouponDialog from './components/CouponDialog.vue'
import CouponService from './services/coupon.service'
import dayjs from 'dayjs'

export default defineComponent({
  name: 'CouponListPage',
  components: {
    Sidebar,
    CouponDialog
  },
  setup(props, { root }) {
    const loading = ref(false)
    const coupons = ref([])
    const total = ref(0)
    const currentPage = ref(1)
    const pageSize = ref(10)

    // Dialog状态
    const isCreateDialogOpen = ref(false)
    const isEditDialogOpen = ref(false)
    const editingCoupon = ref(null)

    // 表格列定义
    const columns = [
      {
        title: '优惠券ID',
        dataIndex: 'id',
        key: 'id',
        width: 100,
        scopedSlots: { customRender: 'id' }
      },
      {
        title: '优惠券类型',
        dataIndex: 'type',
        key: 'type',
        width: 100,
        scopedSlots: { customRender: 'type' }
      },
      {
        title: '优惠券名称',
        dataIndex: 'name',
        key: 'name',
        width: 180,
        scopedSlots: { customRender: 'name' }
      },
      {
        title: '优惠内容',
        key: 'content',
        width: 140,
        scopedSlots: { customRender: 'content' }
      },
      {
        title: '备注',
        dataIndex: 'remark',
        key: 'remark',
        width: 120,
        scopedSlots: { customRender: 'remark' }
      },
      {
        title: '有效天数',
        dataIndex: 'validDays',
        key: 'validDays',
        width: 100,
        scopedSlots: { customRender: 'validDays' }
      },
      {
        title: '有效日期',
        dataIndex: 'validDateRange',
        key: 'validDateRange',
        width: 140,
        scopedSlots: { customRender: 'validDateRange' }
      },
      {
        title: '费用承担',
        key: 'ratio',
        width: 100,
        scopedSlots: { customRender: 'ratio' }
      },
      {
        title: '创建时间',
        dataIndex: 'createdAt',
        key: 'createdAt',
        width: 120,
        scopedSlots: { customRender: 'createdAt' }
      },
      {
        title: '创建人',
        dataIndex: 'createdBy',
        key: 'createdBy',
        width: 100
      },
      {
        title: '操作',
        key: 'action',
        width: 140,
        fixed: 'right',
        scopedSlots: { customRender: 'action' }
      }
    ]

    // 分页配置
    const paginationConfig = reactive({
      current: 1,
      pageSize: 10,
      total: 0,
      showSizeChanger: true,
      showQuickJumper: true,
      showTotal: (total) => `共 ${total} 条`,
      pageSizeOptions: ['10', '20', '50', '100']
    })

    // 获取优惠券列表
    const fetchCoupons = async () => {
      loading.value = true
      try {
        const result = await CouponService.getCoupons({
          page: currentPage.value,
          pageSize: pageSize.value
        })
        coupons.value = result.data
        total.value = result.total
        paginationConfig.total = result.total
        paginationConfig.current = result.page
      } catch (error) {
        root.$message.error('获取优惠券列表失败')
      } finally {
        loading.value = false
      }
    }

    // 表格变化处理
    const handleTableChange = (pagination) => {
      currentPage.value = pagination.current
      pageSize.value = pagination.pageSize
      fetchCoupons()
    }

    // 打开编辑Dialog
    const handleEdit = (coupon) => {
      editingCoupon.value = coupon
      isEditDialogOpen.value = true
    }

    // 切换状态
    const handleToggleStatus = async (coupon) => {
      try {
        await CouponService.toggleCouponStatus(coupon.id)
        root.$message.success(`已${coupon.status === 'enabled' ? '停用' : '启用'}优惠券`)
        fetchCoupons()
      } catch (error) {
        root.$message.error('操作失败')
      }
    }

    // Dialog成功回调
    const handleDialogSuccess = () => {
      isCreateDialogOpen.value = false
      isEditDialogOpen.value = false
      fetchCoupons()
    }

    // 跳转到操作记录
    const goToOperationLogs = () => {
      root.$router.push('/platform-admin/coupon-management/operation-logs')
    }

    // 获取优惠券类型文本
    const getCouponTypeText = (type) => {
      const map = {
        full_reduction: '满减券',
        discount: '折扣券',
        instant_reduction: '立减券'
      }
      return map[type] || type
    }

    // 获取优惠券内容
    const getCouponContent = (coupon) => {
      if (coupon.type === 'full_reduction') {
        return `满${coupon.threshold}元减${coupon.amount}元`
      } else if (coupon.type === 'discount') {
        return `${coupon.discount}折，最高${coupon.maxDiscount}元`
      } else if (coupon.type === 'instant_reduction') {
        return `立减${coupon.amount}元`
      }
      return '-'
    }

    // 获取优惠券类型样式
    const getCouponTypeBadgeClass = (type) => {
      const classMap = {
        full_reduction: 'tag-orange',
        discount: 'tag-green',
        instant_reduction: 'tag-blue'
      }
      return classMap[type] || ''
    }

    // 获取有效天数文本
    const getValidDaysText = (record) => {
      if (record.validDateRange) {
        return '—'
      }
      if (record.validDays === 0) return '永久'
      return record.validDays ? `${record.validDays}天` : '—'
    }

    // 格式化日期
    const formatDate = (datetime) => {
      if (!datetime) return '-'
      return dayjs(datetime).format('YYYY-MM-DD')
    }

    // 格式化时间
    const formatTime = (datetime) => {
      if (!datetime) return '-'
      return dayjs(datetime).format('HH:mm:ss')
    }

    onMounted(() => {
      fetchCoupons()
    })

    return {
      loading,
      coupons,
      columns,
      paginationConfig,
      isCreateDialogOpen,
      isEditDialogOpen,
      editingCoupon,
      handleTableChange,
      handleEdit,
      handleToggleStatus,
      handleDialogSuccess,
      goToOperationLogs,
      getCouponTypeText,
      getCouponContent,
      getCouponTypeBadgeClass,
      getValidDaysText,
      formatDate,
      formatTime
    }
  }
})
</script>

<style scoped lang="less">
@import '@/styles/variables.less';

.coupon-list-page {
  padding: 24px;
  max-width: 1800px;
  margin: 0 auto;
}

// 卡片样式
.list-card {
  border-radius: @border-radius-lg;
  border: 1px solid @border-primary;
  box-shadow: @shadow-sm;

  :deep(.ant-card-head) {
    border-bottom: 1px solid @bg-tertiary;
    padding: 16px 24px;
  }

  :deep(.ant-card-body) {
    padding: 0;
  }
}

.card-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  width: 100%;
}

.card-title {
  font-size: @font-size-lg;
  font-weight: @font-weight-semibold;
  color: @text-primary;
}

.header-actions {
  display: flex;
  gap: 8px;
}

// ID 文本
.id-text {
  font-family: @font-family;
  font-weight: @font-weight-medium;
  color: @text-primary;
  font-size: @font-size-sm;
}

// 名称文本
.name-text {
  color: @text-primary;
  font-size: @font-size-base;
}

// 内容文本
.content-text {
  color: @text-primary;
  font-size: @font-size-sm;
  font-weight: @font-weight-medium;
}

// 备注文本
.remark-text {
  color: @text-primary;
  font-size: @font-size-sm;
  max-width: 120px;
  display: inline-block;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

// 有效期文本
.valid-text {
  color: @text-primary;
  font-size: @font-size-sm;
}

// 日期范围单元格
.date-range-cell {
  .date-line {
    color: @text-primary;
    font-size: @font-size-sm;
    line-height: 1.5;

    &:first-child {
      margin-bottom: 2px;
    }
  }
}

// 费用承担文本
.ratio-text {
  font-size: @font-size-sm;

  div {
    color: @text-primary;
    line-height: 1.5;
  }

  .ratio-merchant {
    color: @text-secondary;
    margin-top: 2px;
  }
}

// 操作按钮
.action-btns {
  display: flex;
  gap: 8px;
  justify-content: center;

  .ant-btn-sm {
    height: 28px;
    padding: 0 12px;
    font-size: @font-size-sm;
  }
}
</style>
